Algoritmo "Contagem"
// ojetivo contar de 1 ate N
Var
// Seção de Declarações das variáveis 
n: inteiro //quantidade a ser contada
i: inteiro // Auxiliar a contagem

Inicio
// Seção de Comandos
escreval ("Até quanto deseja contar?")
leia (n) // pegando a informação do usuário
i <-1 // o auxilair começa em 1 pois
escreval ("contando até ", n)
// estrutura de repetição
enquanto i <= n faça
     escreval (i)
     i <- i+1
fimenquanto
escreval ("Contagem finalizada")
Fimalgoritmo